modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="timtarans_decorations"
version="0.0.0"
displayName="Timtaran's Decorations"
credits="Thanks for MCReator creators"
displayURL="https://timtaran.tk"
authors="Timtaran"
description='''
Minecraft mod for MineScale
'''

[[dependencies.timtarans_decorations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




